### ISSUE TITLE
Unable to connect protobuf serialization

### ISSUE THREAD

**Issue by mushtaq** [cornerman/covenant#3]
I am experimenting if we can use protobuf for serialization with covenant. I have created implicit chameleon Serde for argument as well as return types. But looks like that is not enough. I get the following error 

`could not find implicit value for parameter deserializer: chameleon.Deserializer[_sloth_SequenceFeeder_feed,java.nio.ByteBuffer]`

Error does not tell me for which type a deserializer is missing. I am assuming that only argument and return types of the are required.

**Comment by cornerman** [comment]
This is due to a limitation of how sloth works currently. When having an Api trait, the macro will create case classes for each function. The case class represent the arguments of the function and are used for serializing the arguments; so a method `feed(a1: A1, a2: A2)` in the trait `SequenceFeeder` would generate a case class `_sloth_SequenceFeeder_feed(a1: A1, a2: A2)`. So the error message says that there is no serializer for this case class available.

Which library are you using for protobuf serialization? Does it support automatically generating serializers for case classes?

Can you show me the code, how you connect protobuf to chameleon? You might not need to add implicit serdes for every type, but only once for your librar, but it depends.

**Comment by mushtaq** [comment]
I see. Now that you mentioned it, I also notice the Limitations section on sloth which says

> Your chosen serialization library needs to support serializing case classes, which are generated by the macro for the parameter lists of each method in the API trait.

I am using ScalaPb, so no, it does not do automatic serde for case classes. In fact, the starting point is .proto files which generates case classes which we then map to our domain models (used in the API).

The relevant code is [here](https://github.com/tmtsoftware/esw-sequencer/blob/master/sequencer-api/src/main/scala/tmt/sequencer/rpc/serde/TypeMappings.scala) and [here](https://github.com/tmtsoftware/esw-sequencer/blob/master/sequencer-framework/src/main/scala/tmt/sequencer/rpc/server/Routes.scala).

**Comment by cornerman** [comment]
Hmm, not sure what to do about it right now. I do not really like that sloth generates these case classes, but yet I do not know of a better way to represent serializable argument lists. I would be good to customize this behaviour and implement it differently (e.g. with shapeless). Ideas are definitely welcome.

Alternatively, did you have a look at https://github.com/julien-lafont/protoless? It support automatic derivation of encoders/decoders for case classes. Though, it does not seem to support a schema validation...

**Comment by mushtaq** [comment]
I think you can close this ticket.

Primary purpose of protobuf files for us is allowing cross language
communication which protoless does not give.

But, expecting a Scala-based RPC system like covenant to provide a
mechanism for non-Scala clients also does not make sense. We will find some
other way to address our use-case.

**Comment by cornerman** [comment]
Tracked in https://github.com/cornerman/sloth/issues/10 now.
